import { StyleSheet } from 'react-native';
import { rootColor } from './Theme.style';

export const cardStyle = StyleSheet.create({
    container: {
        position: 'static',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: 80,
    },
    data_product: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        height: '100%',
        borderColor: rootColor.white.smoke,
        borderWidth: 2,
        borderRadius: 10,
    },
    data_payment: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        width: '90%',
        height: '100%',
        borderColor: rootColor.white.smoke,
        borderWidth: 2,
        borderRadius: 10,
    },
    icon: {
        width: 50,
        height: 50,
        marginLeft: 5,
        marginRight: 5,
    },
    title_product: {
        fontSize: 16,
        fontWeight: 'bold',
        lineHeight: 40,
        height: 40,
        width: '50%',
        marginLeft: 5,
        marginRight: 5,
    },
    content_product: {
        fontSize: 16,
        marginLeft: 5,
        marginRight: 5,
    },
    status_product: {
        width: 20,
        height: 20,
        marginLeft: 5,
        marginRight: 5,
    },
    firstData_product: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        width: '70%',
    },
    otherData_product: {
        display: 'flex',
        flexDirection: 'column',
        width: '20%',
        marginRight: '10%',
    },
    secondDataTop_product: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        lineHeight: 40,
        height: 40,
    },
    secondDataBottom_product: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        lineHeight: 40,
        height: 40,
    },
    buttonQuantity_image: {
        width: 20,
        height: 20,
    },
    title_payment: {
        fontSize: 16,
        fontWeight: 'bold',
        lineHeight: 40,
        height: 40,
        width: '50%',
        marginLeft: 5,
        marginRight: 5,
    },
    content_payment: {
        fontSize: 16,
        marginLeft: 5,
        marginRight: 5,
    },
    status_payment: {
        width: 15,
        height: 15,
    },
    firstData_payment: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    secondData_payment: {
        display: 'flex',
        flexDirection: 'column',
    },
    thirdData_payment: {
        display: 'flex',
        flexDirection: 'column',
    },
});