import { StyleSheet } from 'react-native';

export const popupStyle = StyleSheet.create({
    container: {
        position: 'absolute',
        zIndex: 2,
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        width: '100%',
        height: '30%',
    },
    dataContainer: {
        position: 'absolute',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '30%',
        marginTop: 50,
    },
    dataCard: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        height: '100%',
        borderColor: '#f0f0f0',
        borderWidth: 2,
        borderRadius: 10,
    },
    buttonClose_view: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        paddingTop: 10,
        paddingRight: 10,
        width: '95%',
    },
    buttonClose_image: {
        position: 'absolute',
        width: 20,
        height: 20,
    },
    title: {
        fontSize: 16,
        fontWeight: 'bold',
        width: '60%',
        margin: 10,
    },
    content: {
        fontSize: 16,
        margin: 10,
    },
    buttonAdd_view: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        marginTop: '30%',
        marginRight: 10,
        paddingTop: 4,
        paddingBottom: 4,
    },
});